http:
  host: 'localhost'
  port: 8080

db:
  mongodb:
    host: localhost
    # port number is currently not supported, because mongodb+srv cannot have a port number
    port: 27017
    database: myDB
    username: myUser
    password: myPass
    retryWrites: true
    w: majority

redis:
  host: localhost
  port: 6379
  password: examplepass
  db: 4

queue:
  redis:
    host: localhost
    port: 6379
    password: examplepass
    db: 1
  limiter:
    # how much jobs should be executed maximum in a certain amount of time (duration)?
    max: 100
    # duration in ms
    duration: 1000

auth:
  jwt:
    secret: mySecret
    expiresIn: 30d

ratelimiter:
  ttl: 60
  limit: 10

cache:
  redis:
    host: localhost
    port: 6379
    password: myPass
    db: 0
  # TTL in seconds
  ttl: 60
